# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53a98a69ab94aedf8e020201b9b6363f70a6177d8154264037845c01eee90b7d1e774a9e868c503eff40bbc2a2a97c4378b150154796ef35ae78d68d0aac6bef

test:
  secret_key_base: 3623e0f1629544aab1ae0ab0e3856122abd0b306047d5179ec553d6155ec9ab84a1fd2fa41c75f870ac29ca6e34cb5c345a55e252ba81fe24fbd7c071031951a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
